-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggRR5NOtROhn3Ltwx
/MKT7iEgyFBMKxrtLJf+ujnmMjmgCgYIKoZIzj0DAQehRANCAARD7/mhuDQQEoYU
LwYg5RZLf7HLjcY5CZTZi3jabKoG95S3r47FZ/LZMud/tvekP50zHJjIRxTd7Wln
sa+Q6MLn
-----END PRIVATE KEY-----